from django.urls import path
from .views import (
    RegisterView,
    ForgotPasswordView,
    ResetPasswordView,
    UserProfileView,
    TeacherListCreateView,
    TeacherDetailView,
    OfficeStaffListCreateView,
    OfficeStaffDetailView,
    PriceSettingView,
    AppearanceSettingsView,
    StudentListView,
    StudentDetailView,
    StudentExcelImportView,
    UserRoleView,
    PeopleSearchView,
    StudentQuickSearchView,
    MenuPermissionSettingsView,
    MyMenuPermissionsView,
    StaffCredentialsListView,
    StaffCredentialsDetailView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset_password'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('teachers/', TeacherListCreateView.as_view(), name='teacher_list'),
    path('teachers/<int:pk>/', TeacherDetailView.as_view(), name='teacher_detail'),
    path('office-staff/', OfficeStaffListCreateView.as_view(), name='office_staff_list'),
    path('office-staff/<int:pk>/', OfficeStaffDetailView.as_view(), name='office_staff_detail'),
    path('price-settings/', PriceSettingView.as_view(), name='price_settings'),
    path('appearance-settings/', AppearanceSettingsView.as_view(), name='appearance_settings'),
    path('students/', StudentListView.as_view(), name='student_list'),
    path('students/<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('students/import-excel/', StudentExcelImportView.as_view(), name='student_import_excel'),
    path('people-search/', PeopleSearchView.as_view(), name='people_search'),
    path('student-quick-search/', StudentQuickSearchView.as_view(), name='student_quick_search'),
    path('users/<int:pk>/role/', UserRoleView.as_view(), name='user_role'),
    path('menu-permissions/', MenuPermissionSettingsView.as_view(), name='menu_permission_settings'),
    path('my-menu-permissions/', MyMenuPermissionsView.as_view(), name='my_menu_permissions'),
    path('staff-credentials/', StaffCredentialsListView.as_view(), name='staff_credentials_list'),
    path('staff-credentials/<int:pk>/', StaffCredentialsDetailView.as_view(), name='staff_credentials_detail'),
]
