# Generated by Django 5.2.16 on 2026-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='deposit_amount',
            field=models.PositiveIntegerField(blank=True, help_text='مبلغ بیعانه (تومان)', null=True),
        ),
        migrations.AddField(
            model_name='newlead',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
