# Generated by Django 5.2.16 on 2026-07-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_newlead_deposit_amount_newlead_deposit_paid_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('national_code', models.CharField(blank=True, max_length=20)),
                ('discount_percent', models.PositiveIntegerField(help_text='درصد تخفیف (۰ تا ۱۰۰)')),
                ('reason', models.CharField(blank=True, help_text='علت تخفیف', max_length=255)),
                ('valid_until', models.DateField(blank=True, help_text='پایان اعتبار تخفیف', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
