# Generated by Django 5.2.16 on 2026-07-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_newlead_followup1_by_newlead_followup2_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
