# Generated by Django 5.2.15 on 2026-08-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0012_onlinecourseactionrequest'),
        ('leads', '0005_newlead_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='term',
            field=models.ForeignKey(blank=True, help_text='ترمی که این فرد در آن ثبت شده — برای فیلتر ترمی در صفحه\u200cی پیگیری', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.term'),
        ),
        migrations.AddField(
            model_name='unregisteredstudent',
            name='term',
            field=models.ForeignKey(blank=True, help_text='ترمی که این فرد در آن ثبت شده — برای فیلتر ترمی در صفحه\u200cی پیگیری', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.term'),
        ),
    ]
