# Generated by Django 5.2.15 on 2026-09-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_newlead_level_test_fields'),
        ('level_tests', '0014_leveltest_natoos_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='unregisteredstudent',
            name='class_slot',
        ),
        migrations.AddField(
            model_name='newlead',
            name='needs_level_test_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='level_test',
            field=models.ForeignKey(blank=True, help_text='آزمون تعیین\u200cسطحی که خودکار برای این سرنخ ساخته شده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_leads', to='level_tests.leveltest'),
        ),
        migrations.AlterField(
            model_name='newlead',
            name='needs_level_test',
            field=models.BooleanField(default=False, help_text='این فرد برای تعیین سطح به صف مدیر آموزش ارجاع داده شده'),
        ),
    ]
