# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_remove_debtor_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlead',
            name='description',
            field=models.TextField(blank=True, default='', help_text='توضیحات آزاد ثبت‌شده توسط مدیر برای این سرنخ'),
        ),
    ]
