# Generated by Django 5.2.15 on 2026-10-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_debtor_carryover_tracking'),
        ('leads', '0018_debtor_registered_status'),
    ]

    operations = [
    ]
