# Generated by Django 5.2.15 on 2026-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_merge_20261007_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال پیگیری'), ('settled', 'تسویه شد')], default='pending', max_length=10),
        ),
    ]
