# Generated by Django 5.2.15 on 2026-10-07 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0030_classslotenrollment_carryover_tracking'),
        ('leads', '0020_alter_debtor_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredstudent',
            name='dropout_from_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.term'),
        ),
        migrations.AddField(
            model_name='unregisteredstudent',
            name='is_dropout',
            field=models.BooleanField(default=False, help_text='ریزشی استخراج\u200cشده از مقایسه\u200cی اکسل دو ترم متوالی'),
        ),
        migrations.CreateModel(
            name='ExcelDropout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='class_management.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_dropouts', to=settings.AUTH_USER_MODEL)),
                ('to_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='class_management.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'from_term', 'to_term'), name='uniq_excel_dropout_pair')],
            },
        ),
    ]
