# Generated by Django 5.2.15 on 2026-10-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0030_classslotenrollment_carryover_tracking'),
        ('leads', '0021_unregisteredstudent_dropout_from_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredstudent',
            name='is_misplaced',
            field=models.BooleanField(default=False, help_text='در کلاس درست ثبت\u200cنام نشده — جابجا شود'),
        ),
        migrations.AddField(
            model_name='unregisteredstudent',
            name='misplaced_from_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.classslot'),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debt_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
