# Generated by Django 5.2.15 on 2026-10-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0030_classslotenrollment_carryover_tracking'),
        ('leads', '0023_unregistered_class_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredstudent',
            name='class_slot',
            field=models.ForeignKey(blank=True, help_text='کلاسی که فرد برای آن ثبت شده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unregistered_students', to='class_management.classslot'),
        ),
    ]
