# Generated by Django 6.0.6 on 2026-07-04 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('age_group', models.CharField(choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10)),
                ('level', models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('U5', 'U5'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('Teen1', 'Teen1'), ('Teen2', 'Teen2'), ('Teen3', 'Teen3'), ('Teen4', 'Teen4'), ('Teen5', 'Teen5'), ('Teen6', 'Teen6'), ('Teen7', 'Teen7'), ('Teen8', 'Teen8'), ('Teen9', 'Teen9'), ('Teen10', 'Teen10'), ('Teen11', 'Teen11'), ('Teen12', 'Teen12'), ('Teen13', 'Teen13'), ('Teen14', 'Teen14'), ('Teen15', 'Teen15'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('306', '306'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('406', '406'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505'), ('506', '506'), ('601', '601'), ('602', '602'), ('603', '603'), ('604', '604'), ('605', '605'), ('606', '606')], max_length=10)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('evaluator_name', models.CharField(blank=True, help_text='برای وقتی ارزیاب حساب کاربری ندارد و مدیر به\u200cجایش وارد می\u200cکند', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_tests_created', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, limit_choices_to={'role': 'evaluator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='level_tests_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
    ]
