# Generated by Django 6.0.6 on 2026-07-04 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leveltest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='leveltest',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='national_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تعیین سطح'), ('completed', 'تعیین سطح شده')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='age_group',
            field=models.CharField(blank=True, choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='level',
            field=models.CharField(blank=True, choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('U5', 'U5'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('Teen1', 'Teen1'), ('Teen2', 'Teen2'), ('Teen3', 'Teen3'), ('Teen4', 'Teen4'), ('Teen5', 'Teen5'), ('Teen6', 'Teen6'), ('Teen7', 'Teen7'), ('Teen8', 'Teen8'), ('Teen9', 'Teen9'), ('Teen10', 'Teen10'), ('Teen11', 'Teen11'), ('Teen12', 'Teen12'), ('Teen13', 'Teen13'), ('Teen14', 'Teen14'), ('Teen15', 'Teen15'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('306', '306'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('406', '406'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505'), ('506', '506'), ('601', '601'), ('602', '602'), ('603', '603'), ('604', '604'), ('605', '605'), ('606', '606')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
