# Generated by Django 6.0.6 on 2026-07-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0002_alter_leveltest_options_leveltest_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTestPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, help_text='قیمت پیش\u200cفرض هر آزمون تعیین سطح (تومان) — می\u200cتواند ۰/رایگان باشد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='leveltest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='قیمت این آزمون — پیش\u200cفرض از تنظیمات، ولی همیشه قابل ویرایش برای هر مورد', null=True),
        ),
    ]
