# Generated by Django 5.2.15 on 2026-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0004_leveltest_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltest',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'خانم'), ('male', 'آقا')], help_text='برای ساخت خودکار حساب دانش\u200cآموز وقتی تعیین\u200cسطح تکمیل می\u200cشود لازم است', max_length=10),
        ),
    ]
