# Generated by Django 5.2.15 on 2026-08-08 16:46

import level_tests.levels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0005_leveltest_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد سطح، مثلاً E1 یا Teen3 یا 305', max_length=20, unique=True)),
                ('age_group', models.CharField(choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش داخل گروه سنی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['age_group', 'order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='leveltest',
            name='level',
            field=models.CharField(blank=True, choices=level_tests.levels.get_all_level_choices, max_length=10),
        ),
    ]
