# Generated by Django 5.2.15 on 2026-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0006_standardlevel_alter_leveltest_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltest',
            name='meeting_link',
            field=models.CharField(blank=True, help_text='لینک تعیین\u200cسطح آنلاین — مدیر بعد از هماهنگی وارد می\u200cکند و برای دانش\u200cآموز در اپ نمایش داده می\u200cشود', max_length=300),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='mode',
            field=models.CharField(blank=True, choices=[('online', 'آنلاین'), ('onsite', 'حضوری')], help_text='آنلاین/حضوری — انتخاب دانش\u200cآموز موقع درخواست از اپ', max_length=10),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'کارت به کارت'), ('gateway', 'درگاه پرداخت')], max_length=10),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='level_test_receipts/'),
        ),
        migrations.AddField(
            model_name='leveltest',
            name='self_requested',
            field=models.BooleanField(default=False, help_text='آیا این رکورد را خودِ دانش\u200cآموز از اپ درخواست داده (نه مدیر/کانتر)'),
        ),
    ]
