# Generated by Django 5.2.15 on 2026-08-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0008_standardlevel_is_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardlevel',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش داخل گروه سنی — همان ترتیب استاندارد پیشرفت سطح'),
        ),
    ]
