# Generated by Django 5.2.15 on 2026-08-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0009_alter_leveltest_level_max_length'),
        ('level_tests', '0009_alter_standardlevel_order'),
    ]

    operations = [
    ]
