# Generated by Django 5.2.15 on 2026-09-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0008_standardlevel_book_title'),
        ('level_tests', '0010_merge_20260829_1732'),
    ]

    operations = [
    ]
