# Generated by Django 5.2.15 on 2026-09-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0011_merge_20260901_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardlevel',
            name='book_title',
        ),
    ]
