# Generated by Django 6.1.1 on 2026-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_tests', '0012_remove_standardlevel_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardlevel',
            name='book',
            field=models.CharField(blank=True, help_text='نام کتاب درسی این سطح، مثلاً «Supermind 2» یا «Project 1» یا «Evolve 3»', max_length=50),
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='final_units',
            field=models.CharField(blank=True, help_text='بازه\u200cی یونیت\u200cهای تحت پوشش پایان\u200cترم (جلسه ۱۵)، مثلاً «Units 1-8»', max_length=100),
        ),
        migrations.AddField(
            model_name='standardlevel',
            name='midterm_units',
            field=models.CharField(blank=True, help_text='بازه\u200cی یونیت\u200cهای تحت پوشش میان\u200cترم (جلسه ۸)، مثلاً «Units 1-4»', max_length=100),
        ),
    ]
