# Generated by Django 6.0.5 on 2026-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_birth_date_user_language_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
