# Generated by Django 6.0.5 on 2026-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='language',
        ),
        migrations.AddField(
            model_name='classrequest',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
