# Generated by Django 6.0.5 on 2026-06-09 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_classrequest_language_classrequest_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='referred_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='class_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='class_date_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='class_type',
            field=models.CharField(choices=[('private', 'خصوصی'), ('makeup', 'جبرانی')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='satisfaction_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='school_share',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='session_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='session_duration',
            field=models.CharField(choices=[('1', 'یک ساعت'), ('1.5', 'یک و نیم ساعت')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='teacher_share',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'مختومه')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='PriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_hour_price', models.PositiveIntegerField(default=400000)),
                ('one_half_hour_price', models.PositiveIntegerField(default=550000)),
                ('teacher_share_percent', models.PositiveIntegerField(default=70)),
                ('school_share_percent', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
