# Generated by Django 6.0.5 on 2026-06-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_classrequest_assigned_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='custom_class_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='teacher_payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='teacher_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='teacher_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='class_type',
            field=models.CharField(choices=[('private', 'خصوصی'), ('makeup', 'جبرانی'), ('other', 'سایر')], default='private', max_length=10),
        ),
    ]
