# Generated by Django 5.2.15 on 2026-06-18 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classrequest_custom_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='accepted_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='accepted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='proposed_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('referred', 'ارجاع\u200cشده به استاد'), ('confirmed', 'تایید نهایی - منتظر برگزاری'), ('completed', 'مختومه'), ('rejected', 'رد شده'), ('cancelled', 'کنسل شده')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
