# Generated by Django 6.0.6 on 2026-07-03 13:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classrequest_custom_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='accepted_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='accepted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='satisfaction_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='suggested_teacher_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='proposed_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='session_duration',
            field=models.CharField(choices=[('1', 'یک ساعت'), ('1.5', 'یک و نیم ساعت')], default='1.5', max_length=5),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('referred', 'ارجاع\u200cشده به استاد'), ('confirmed', 'تایید نهایی - منتظر برگزاری'), ('completed', 'مختومه'), ('rejected', 'رد شده'), ('cancelled', 'کنسل شده')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
