# Generated by Django 5.2.15 on 2026-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_classrequest_accepted_teachers_alter_classrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='satisfaction_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10),
        ),
    ]
