# Generated by Django 6.0.6 on 2026-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_classrequest_accepted_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز'), ('evaluator', 'ارزیاب (تعیین سطح)')], default='student', max_length=10),
        ),
    ]
