# Generated by Django 6.0.6 on 2026-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز'), ('evaluator', 'مدیر آموزش')], default='student', max_length=10),
        ),
    ]
