# Generated by Django 6.0.6 on 2026-07-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrequest',
            name='accepted_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, related_name='accepted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, related_name='referred_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
