# Generated by Django 5.2.16 on 2026-07-10 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_classrequest_accepted_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='این فیلد فقط باید با حروف فارسی نوشته شود (نه انگلیسی یا اعداد لاتین).', regex='^[\\u0600-\\u06FF\\s\\u200C]+$')]),
        ),
        migrations.AlterField(
            model_name='classrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='نام کاربری فقط می\u200cتواند شامل حروف انگلیسی (کوچک/بزرگ)، اعداد و کاراکترهای خاص انگلیسی باشد (بدون فاصله و بدون حروف فارسی).', regex='^[A-Za-z0-9!@#$%^&*()_+\\-=\\[\\]{};:\\\'",.<>\\/?~`|\\\\]+$')]),
        ),
    ]
