# Generated by Django 5.2.16 on 2026-07-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_father_name_alter_classrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر'), ('teacher', 'معلم'), ('student', 'دانش\u200cآموز'), ('evaluator', 'مدیر آموزش'), ('office', 'اداری')], default='student', max_length=10),
        ),
    ]
