# Generated by Django 5.2.15 on 2026-08-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_wallet_balance_alter_classrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='is_online',
            field=models.BooleanField(default=False, help_text='کلاس آنلاین است — دقیقاً همان شرایط کلاس\u200cهای آنلاین ترمیک را دارد؛ بعد از تایید نهایی، لینک به اپ استاد و دانش\u200cآموز نمایش داده می\u200cشود'),
        ),
        migrations.AddField(
            model_name='classrequest',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
