# Generated by Django 5.2.15 on 2026-08-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_classrequest_is_online_classrequest_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='یکتا بودن این فیلد الزامی نیست — چون معمولاً چند خواهر/برادر با یک شماره موبایلِ والدین ثبت\u200cنام می\u200cشوند', max_length=11),
        ),
    ]
