# Generated by Django 5.2.15 on 2026-08-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrequest',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
