# Generated by Django 5.2.15 on 2026-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_classrequest_seen_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrequest',
            name='seen_by_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='needs_editing',
            field=models.BooleanField(default=False, help_text='برای دانش\u200cآموزی که فقط با اطلاعات حداقلی از «ثبت\u200cنام مستقیم» ساخته شده (بدون تاریخ تولد/آدرس و...)؛ در «مدیریت دانش\u200cآموزان» علامت\u200cگذاری می\u200cشود تا مدیر یادش بماند اطلاعات را بعداً تکمیل کند.'),
        ),
    ]
