# Generated by Django 5.2.15 on 2026-08-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_appearancesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearancesettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
