# Generated by Django 5.2.15 on 2026-09-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_menupermission_can_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='can_edit',
            field=models.BooleanField(default=False, help_text='انجام کارهای این صفحه (ثبت/ویرایش/حذف) — نه فقط دیدن'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
