# Generated by Django 5.2.15 on 2026-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_attendanceaccesssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceaccesssettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
