# Generated by Django 5.2.15 on 2026-09-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_attendanceaccesssettings_id'),
        ('accounts', '0029_appaccesssettings'),
    ]

    operations = [
    ]
