# Generated by Django 5.2.15 on 2026-09-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_20260910_1409'),
        ('accounts', '0030_mobilemenuvisibility'),
    ]

    operations = [
    ]
