# Generated by Django 5.2.15 on 2026-09-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_classrequest_group_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrequest',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, help_text='برای کلاس خصوصی چند نفره — همه\u200cی اعضای یک کلاس مشترک، این مقدار را یکسان دارند', max_length=40),
        ),
    ]
