# Generated by Django 5.2.15 on 2026-09-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_classrequest_group_key'),
        ('accounts', '0034_price_setting_group_pricing_and_group_size'),
    ]

    operations = [
    ]
