# Generated by Django 5.2.15 on 2026-09-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_dailyactivity'),
        ('accounts', '0035_merge_20260920_1005'),
    ]

    operations = [
    ]
