"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(%3%8g$u*f03t^kcs7i@!@wc)!wj7x4$#^s9wh9%k(=fbc0%=3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'accounts',
    'classes.apps.ClassesConfig',
    'notifications',
    'group_classes',
    'level_tests',
    'staff_messages',
    'library',
    'leads',
    'class_management',
    'grading',
    'payroll',
    'reports',
    'django_jalali',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8081',
    'http://192.168.1.109:8081',
]
# اجازه‌ی دسترسی از هر دستگاه دیگری در همان شبکه‌ی محلی (وای‌فای خانه/دفتر) — چون آی‌پی
# دستگاه‌ها با وای‌فای معمولاً هر بار عوض می‌شود، به‌جای اضافه‌کردن دستیِ هر آی‌پی، این سه بازه‌ی
# رایجِ شبکه‌ی محلی (192.168.x.x / 10.x.x.x / 172.16-31.x.x) به‌صورت عمومی مجاز شده‌اند —
# پورت‌های ۳۰۰۰ (پنل ادمین) و ۸۰۸۱ (اپ موبایل/Expo) هر دو پوشش داده شده‌اند.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^http://192\.168\.\d{1,3}\.\d{1,3}:(3000|8081)$',
    r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}:(3000|8081)$',
    r'^http://172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}:(3000|8081)$',
]

# ---- Web Push (اعلان ناتیو صدادار ویندوز/مک برای ادمین/اداری، حتی وقتی پنل بسته است) ----
# این کلیدها یک‌بار تولید و اینجا ثابت شده‌اند — اگر روزی خواستید عوضشان کنید، هر اشتراکِ
# مرورگرِ قبلی باطل می‌شود و کاربران باید یک‌بار دیگر «فعال‌سازی اعلان» را بزنند.
# ⚠️ توجه مهم: Web Push فقط روی HTTPS یا روی «localhost» کار می‌کند — روی آی‌پی شبکه‌ی محلی
# با HTTP ساده (مثل http://192.168.x.x:3000) مرورگرها اجازه‌ی subscribe نمی‌دهند. برای تست
# محلی از خودِ کامپیوتر سرور با «localhost:3000» وارد شوید؛ روی دامنه‌ی نهاییِ HTTPS در آینده
# بدون هیچ تغییری کار خواهد کرد.
VAPID_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgMxJPy6qwbSfda/De
eWBP1LitPuBHze6UyzSVoYXy1fyhRANCAAR2CtHwGYq7MgqRyLB6XMMUnEjDwKuf
f/WEaaPqfSkDUz18esUcp9WfPl4iMdXiSrOTpv2ROCgjYodiyVFiuZTs
-----END PRIVATE KEY-----"""
VAPID_PUBLIC_KEY = 'BHYK0fAZirsyCpHIsHpcwxScSMPAq59_9YRpo-p9KQNTPXx6xRyn1Z8-XiIx1eJKs5Om_ZE4KCNih2LJUWK5lOw'
VAPID_CLAIM_EMAIL = 'mailto:admin@example.com'