# Generated by Django 6.1 on 2026-08-22 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_key', models.CharField(help_text='کلید منبع داده — از reports/registry_custom.py', max_length=50)),
                ('fields', models.JSONField(default=list, help_text='لیست کلید فیلدهای انتخابی برای نمایش تخت (بدون گروه\u200cبندی)')),
                ('filters', models.JSONField(default=list, help_text="لیست شرط\u200cها: [{'field','op','value'}, ...]")),
                ('group_by', models.JSONField(blank=True, default=list, help_text='لیست کلید فیلدهای گروه\u200cبندی (اختیاری)')),
                ('aggregations', models.JSONField(blank=True, default=list, help_text="[{'field','func'}, ...] — فقط وقتی group_by پر باشد معنی دارد")),
                ('date_override', models.BooleanField(default=False, help_text='اگر True باشد، فیلتر تاریخ سراسری صفحه روی این گزارش اعمال نمی\u200cشود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
