# Generated by Django 5.2.16 on 2026-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitpermissionrequest',
            name='coordination_person',
            field=models.CharField(blank=True, help_text='نام فرد جهت هماهنگی ورود/خروج', max_length=150),
        ),
        migrations.AddField(
            model_name='entryexitpermissionrequest',
            name='coordination_phone',
            field=models.CharField(blank=True, help_text='شماره تماس جهت هماهنگی ورود/خروج', max_length=20),
        ),
    ]
