# Generated by Django 5.2.16 on 2026-07-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_messages', '0002_entryexitpermissionrequest_coordination_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitpermissionrequest',
            name='teacher_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
