from django.urls import path
from .views import (
    GroupSessionListCreateView,
    GroupSessionDetailView,
    JoinGroupSessionView,
    LeaveGroupSessionView,
    CloseRegistrationView,
    AssignTeachersView,
    TeacherAcceptView,
    TeacherDeclineView,
    FinalizeGroupSessionView,
    CancelGroupSessionView,
    GroupSessionMeetingListView,
    GroupSessionMeetingUpdateView,
    AdminConfirmCompleteView,
    ParticipantSatisfactionView,
    ApproveParticipantSatisfactionView,
    ParticipantPaymentView,
    GroupPriceSettingView,
)

urlpatterns = [
    path('group-classes/price-setting/', GroupPriceSettingView.as_view(), name='group_price_setting'),
    path('group-classes/sessions/', GroupSessionListCreateView.as_view(), name='group_session_list'),
    path('group-classes/sessions/<int:pk>/', GroupSessionDetailView.as_view(), name='group_session_detail'),
    path('group-classes/sessions/<int:pk>/join/', JoinGroupSessionView.as_view(), name='group_session_join'),
    path('group-classes/sessions/<int:pk>/leave/', LeaveGroupSessionView.as_view(), name='group_session_leave'),
    path('group-classes/sessions/<int:pk>/close-registration/', CloseRegistrationView.as_view(), name='group_session_close'),
    path('group-classes/sessions/<int:pk>/assign/', AssignTeachersView.as_view(), name='group_session_assign'),
    path('group-classes/sessions/<int:pk>/accept/', TeacherAcceptView.as_view(), name='group_session_accept'),
    path('group-classes/sessions/<int:pk>/decline/', TeacherDeclineView.as_view(), name='group_session_decline'),
    path('group-classes/sessions/<int:pk>/finalize/', FinalizeGroupSessionView.as_view(), name='group_session_finalize'),
    path('group-classes/sessions/<int:pk>/cancel/', CancelGroupSessionView.as_view(), name='group_session_cancel'),
    path('group-classes/sessions/<int:pk>/confirm-complete/', AdminConfirmCompleteView.as_view(), name='group_session_confirm_complete'),
    path('group-classes/sessions/<int:pk>/meetings/', GroupSessionMeetingListView.as_view(), name='group_session_meetings'),
    path('group-classes/sessions/<int:pk>/meetings/<int:meeting_number>/', GroupSessionMeetingUpdateView.as_view(), name='group_session_meeting_update'),
    path('group-classes/sessions/<int:pk>/satisfaction/', ParticipantSatisfactionView.as_view(), name='group_session_satisfaction'),
    path('group-classes/sessions/<int:pk>/approve-satisfaction/', ApproveParticipantSatisfactionView.as_view(), name='group_session_approve_satisfaction'),
    path('group-classes/sessions/<int:pk>/participants/<int:participant_id>/payment/', ParticipantPaymentView.as_view(), name='group_session_participant_payment'),
]
