# Generated by Django 5.2.16 on 2026-07-18 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_degree', models.CharField(blank=True, help_text='مدرک تحصیلی', max_length=50)),
                ('education_field', models.CharField(blank=True, help_text='رشته تحصیلی', max_length=100)),
                ('hire_date', models.DateField(blank=True, help_text='تاریخ استخدام', null=True)),
                ('address', models.TextField(blank=True, help_text='آدرس محل سکونت')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10)),
                ('children_count', models.PositiveIntegerField(default=0, help_text='تعداد فرزندان (در صورت تاهل)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('daily', 'روزانه'), ('hourly', 'ساعتی')], default='daily', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='برای مرخصی روزانه\u200cی چندروزه', null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='برای مرخصی ساعتی', max_digits=5, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveIntegerField()),
                ('annual_days', models.PositiveIntegerField(default=0, help_text='عدد مرخصی روزانه\u200cی مجاز در این سال')),
                ('hourly_allowance', models.DecimalField(decimal_places=2, default=0, help_text='مقدار مجاز مرخصی ساعتی در این سال', max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jalali_year'],
                'constraints': [models.UniqueConstraint(fields=('user', 'jalali_year'), name='unique_leave_balance_per_user_year')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_year', models.PositiveIntegerField()),
                ('jalali_month', models.PositiveIntegerField(help_text='۱ تا ۱۲')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, help_text='ساعات کارکرد این ماه', max_digits=6)),
                ('insurance_days', models.PositiveIntegerField(default=30, help_text='تعداد روزهای بیمه\u200cی این ماه (کسورات)')),
                ('insurance_amount', models.PositiveIntegerField(default=0, help_text='حق بیمه\u200cی ماهانه — کسر می\u200cشود (تومان)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jalali_year', '-jalali_month'],
                'constraints': [models.UniqueConstraint(fields=('user', 'jalali_year', 'jalali_month'), name='unique_payroll_per_user_month')],
            },
        ),
        migrations.CreateModel(
            name='SalaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_year', models.PositiveIntegerField(help_text='سال کاری شمسی، مثلاً ۱۴۰۴')),
                ('base_salary', models.PositiveIntegerField(default=0, help_text='حداقل حقوق پایه\u200cی سال کاری (تومان)')),
                ('food_allowance', models.PositiveIntegerField(default=0, help_text='حق خوار و بار')),
                ('marriage_allowance', models.PositiveIntegerField(default=0, help_text='حق تاهل')),
                ('child_allowance', models.PositiveIntegerField(default=0, help_text='حق اولاد')),
                ('seniority_allowance', models.PositiveIntegerField(default=0, help_text='سنوات سالانه (حق سنوات)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-work_year'],
                'constraints': [models.UniqueConstraint(fields=('user', 'work_year'), name='unique_salary_profile_per_user_year')],
            },
        ),
    ]
