# Generated by Django 5.2.16 on 2026-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='hourly_allowance',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='insurance_amount',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='monthly_hourly_allowance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مقدار مجاز مرخصی ساعتی — در هر ماه (نه کل سال)', max_digits=6),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_category',
            field=models.CharField(choices=[('entitled', 'استحقاقی'), ('sick', 'استعلاجی'), ('other', 'سایر')], default='entitled', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='absence_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='غیبت (روز) — کسر می\u200cشود', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='absence_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='غیبت (ساعت) — کسر می\u200cشود', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='bonus_amount',
            field=models.PositiveIntegerField(default=0, help_text='پاداش (تومان) — مستقیم اضافه می\u200cشود'),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='اضافه\u200cکاری (ساعت) — با نرخ ۱٫۴ برابر اضافه می\u200cشود', max_digits=6),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='undertime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='کم\u200cکاری (ساعت) — کسر می\u200cشود', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='insurance_rate_30_days',
            field=models.PositiveIntegerField(default=0, help_text='حق بیمه\u200cی مصوبِ این سال برای ۳۰ روز کامل (تومان)'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(blank=True, help_text='برای دسته\u200cی «سایر» الزامی است', max_length=255),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='insurance_days',
            field=models.PositiveIntegerField(default=30, help_text='تعداد روزهای بیمه\u200cی این ماه'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='base_salary',
            field=models.PositiveIntegerField(default=0, help_text='حداقل حقوق پایه\u200cی سال کاری (تومان، ماهانه)'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='child_allowance',
            field=models.PositiveIntegerField(default=0, help_text='حق اولاد (ماهانه)'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='food_allowance',
            field=models.PositiveIntegerField(default=0, help_text='حق خوار و بار (ماهانه)'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='marriage_allowance',
            field=models.PositiveIntegerField(default=0, help_text='حق تاهل (ماهانه)'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='seniority_allowance',
            field=models.PositiveIntegerField(default=0, help_text='سنوات سالانه — حق سنوات (معادل ماهانه\u200cاش اینجا وارد می\u200cشود)'),
        ),
    ]
