# Generated by Django 6.0.7 on 2026-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_leavebalance_hourly_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='شماره حساب بانکی', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='card_number',
            field=models.CharField(blank=True, help_text='شماره کارت بانکی', max_length=16),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='sheba_number',
            field=models.CharField(blank=True, help_text='شماره شبا (بدون IR)', max_length=26),
        ),
    ]
