# Generated by Django 6.0.7 on 2026-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeeprofile_bank_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryprofile',
            name='insurance_rate_30_days',
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='extra_payment',
            field=models.PositiveIntegerField(default=0, help_text='اضافه\u200cپرداخت این ماه (تومان) — مستقیم به ناخالص اضافه می\u200cشود'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='housing_allowance_yearly',
            field=models.PositiveIntegerField(default=0, help_text='حق مسکن سالانه (تومان) — معادل ماهانه/روزانه/ساعتی\u200cاش خودکار محاسبه می\u200cشود'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='insurance_base_married',
            field=models.PositiveIntegerField(default=0, help_text='مزد مبنای بیمه برای کارمند متاهل (۳۰ روز کامل، تومان)'),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='insurance_base_single',
            field=models.PositiveIntegerField(default=0, help_text='مزد مبنای بیمه برای کارمند مجرد (۳۰ روز کامل، تومان)'),
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ساعات کارکرد این ماه — فعلاً دستی وارد و قابل\u200cویرایش است. در آینده وقتی صفحه\u200cی «ثبت ورود و خروج» ساخته شد، باید این مقدار به\u200cصورت خودکار از آنجا محاسبه و پر شود، ولی همچنان دستی هم قابل\u200cاصلاح بماند.', max_digits=6),
        ),
    ]
