# Generated by Django 5.2.15 on 2026-08-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_salaryprofile_insurance_rate_30_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryprofile',
            name='housing_allowance',
            field=models.PositiveIntegerField(default=0, help_text='حق مسکن ماهانه (تومان) — مستقیم ماهانه وارد می\u200cشود'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='housing_allowance_yearly',
            field=models.PositiveIntegerField(default=0, help_text='(قدیمی/غیرفعال — دیگر استفاده نمی\u200cشود) حق مسکن سالانه؛ برای سازگاری با داده\u200cهای قبلی نگه داشته شده'),
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='seniority_allowance',
            field=models.PositiveIntegerField(default=0, help_text='(قدیمی/غیرفعال — دیگر استفاده نمی\u200cشود) از این پس «پایه سنوات» خودکار از روی سابقه\u200cکار محاسبه می\u200cشود؛ این فیلد فقط برای سازگاری با داده\u200cهای قبلی نگه داشته شده'),
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='تاریخ (میلادی ذخیره می\u200cشود) — روزی که این ثبت مربوط به آن است')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('edited_by_admin', models.BooleanField(default=False, help_text='اگر مدیر دستی این رکورد را اصلاح کرده باشد True می\u200cشود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_attendance_per_user_day')],
            },
        ),
    ]
