# Generated by Django 5.2.15 on 2026-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_salaryprofile_housing_allowance_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salaryprofile',
            name='unique_salary_profile_per_user_year',
        ),
        migrations.RemoveField(
            model_name='salaryprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='salaryprofile',
            name='work_year',
            field=models.PositiveIntegerField(help_text='سال کاری شمسی، مثلاً ۱۴۰۴ — برای کل مجموعه یکتا', unique=True),
        ),
    ]
