# Generated by Django 5.2.15 on 2026-08-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_employee_minimum_hours_and_adjustment_thresholds'),
        ('payroll', '0008_salaryprofile_payroll_thresholds'),
    ]

    operations = [
    ]
