# Generated by Django 5.2.15 on 2026-08-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_merge_20260827_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='minimum_monthly_hours',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='auto_adjustments_enabled',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='automatic_adjustment_note',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='automatic_carryover_hours',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='automatic_leave_days',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='hourly_shortfall_threshold',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='leave_day_threshold',
        ),
        migrations.RemoveField(
            model_name='salaryprofile',
            name='hourly_shortfall_threshold',
        ),
        migrations.RemoveField(
            model_name='salaryprofile',
            name='leave_day_threshold',
        ),
        migrations.RemoveField(
            model_name='salaryprofile',
            name='shortfall_hourly_threshold',
        ),
        migrations.RemoveField(
            model_name='salaryprofile',
            name='shortfall_leave_day_threshold',
        ),
    ]
