# Generated by Django 5.2.15 on 2026-08-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_merge_payroll_migrations'),
        ('payroll', '0010_remove_employeeprofile_minimum_monthly_hours_and_more'),
    ]

    operations = [
    ]
