# Generated by Django 5.2.15 on 2026-08-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_mixed_leave_and_official_holidays'),
        ('payroll', '0011_merge_20260827_0900'),
    ]

    operations = [
    ]
