# Generated by Django 5.2.15 on 2026-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_merge_20260827_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='minimum_monthly_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='حداقل ساعات کارکرد ماهانه این کارمند؛ صفر یعنی ساعت استاندارد ماه', max_digits=6),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='shortfall_hourly_threshold',
            field=models.DecimalField(decimal_places=2, default=2.5, help_text='حداکثر کسری\u200cساعت برای کسر ساعتی', max_digits=4),
        ),
        migrations.AddField(
            model_name='salaryprofile',
            name='shortfall_leave_day_threshold',
            field=models.DecimalField(decimal_places=2, default=5, help_text='از این مقدار کسری به بعد یک روز مرخصی کسر می\u200cشود', max_digits=4),
        ),
        migrations.AlterField(
            model_name='holidayworkassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='officialholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
