# Generated by Django 6.1.1 on 2026-09-04 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0024_classattendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePassingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10, unique=True)),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='حداقل نمره قبولی از ۱۰۰')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10)),
                ('field_key', models.CharField(choices=[('cp', 'CP'), ('midterm', 'میان\u200cترم'), ('writing1', 'رایتینگ ۱'), ('writing2', 'رایتینگ ۲'), ('final', 'پایان\u200cترم')], max_length=20)),
                ('title', models.CharField(help_text='عنوان نمایشی این فیلد برای این رده سنی — قابل ویرایش', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='آیا این فیلد برای این رده سنی فعال است')),
                ('max_score', models.PositiveIntegerField(default=0, help_text='سهم این فیلد از نمره\u200cی نهایی ۱۰۰ (وقتی فعال است)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['age_group', 'order'],
                'constraints': [models.UniqueConstraint(fields=('age_group', 'field_key'), name='unique_grade_field_per_age_group')],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, help_text='سطح کلاس در لحظه\u200cی ثبت/قطعی\u200cشدن نمره', max_length=50)),
                ('age_group', models.CharField(blank=True, help_text='رده سنی محاسبه\u200cشده از روی سطح کلاس', max_length=10)),
                ('cp_score', models.PositiveIntegerField(blank=True, null=True)),
                ('midterm_score', models.PositiveIntegerField(blank=True, null=True)),
                ('writing1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('writing2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('final_score', models.PositiveIntegerField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_fail', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='class_management.classslot')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades', to='class_management.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['term', 'student'], name='grading_stu_term_id_854ae0_idx'), models.Index(fields=['class_slot', 'is_finalized'], name='grading_stu_class_s_eed23c_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_slot', 'student'), name='unique_grade_per_student_per_class')],
            },
        ),
    ]
