# Generated by Django 6.0.6 on 2026-07-04 05:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPriceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_two', models.PositiveIntegerField(default=0, help_text='قیمت هرنفر وقتی کلاس خصوصی گروهی دقیقاً ۲ نفره است')),
                ('price_for_three_plus', models.PositiveIntegerField(default=0, help_text='قیمت هرنفر وقتی کلاس خصوصی گروهی ۳ نفر یا بیشتر است')),
                ('teacher_share_percent', models.PositiveIntegerField(default=70)),
                ('school_share_percent', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('workshop', 'ورکشاپ'), ('private_group', 'خصوصی گروهی')], max_length=20)),
                ('title', models.CharField(blank=True, help_text='عنوان ورکشاپ (اختیاری). برای خصوصی گروهی خودکار ساخته می\u200cشود', max_length=200)),
                ('language_level', models.CharField(max_length=50)),
                ('class_date', models.DateTimeField(blank=True, null=True)),
                ('session_duration', models.CharField(choices=[('1', 'یک ساعت'), ('1.5', 'یک و نیم ساعت')], default='1.5', max_length=5)),
                ('session_count', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('price_per_person', models.PositiveIntegerField(blank=True, help_text='فقط برای ورکشاپ؛ می\u200cتواند ۰ (رایگان) باشد', null=True)),
                ('status', models.CharField(choices=[('open', 'باز برای ثبت\u200cنام'), ('assigning', 'ارجاع به استاد'), ('confirmed', 'تایید نهایی'), ('completed', 'مختومه'), ('rejected', 'رد شده'), ('cancelled', 'کنسل شده')], default='open', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='group_sessions_accepted', to=settings.AUTH_USER_MODEL)),
                ('assigned_teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='group_sessions_referred', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions_teaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSessionMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='group_classes.groupsession')),
            ],
            options={
                'ordering': ['meeting_number'],
                'unique_together': {('group_session', 'meeting_number')},
            },
        ),
        migrations.CreateModel(
            name='GroupSessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('pending', 'در انتظار تایید')], default='unpaid', max_length=10)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='group_receipts/')),
                ('satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('satisfaction_text', models.TextField(blank=True)),
                ('satisfaction_approved', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='group_classes.groupsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('group_session', 'student')},
            },
        ),
    ]
