# Generated by Django 6.0.6 on 2026-07-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsession',
            name='accepted_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, related_name='group_sessions_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, related_name='group_sessions_referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupsession',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'evaluator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions_teaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
