# Generated by Django 5.2.16 on 2026-07-10 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_classes', '0002_alter_groupsession_accepted_teachers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='price_per_session',
            field=models.PositiveIntegerField(blank=True, help_text='قیمت هرنفر برای هر جلسه (اختیاری). اگر پر شود، قیمت کل هرنفر = این مقدار × تعداد جلسات', null=True),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='teacher_share_percent_override',
            field=models.PositiveIntegerField(blank=True, help_text='درصد اختصاصی سهم استاد برای همین جلسه (اختیاری). اگر خالی باشد، از تنظیمات مشترک استفاده می\u200cشود', null=True),
        ),
        migrations.CreateModel(
            name='GroupSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unmarked', 'ثبت\u200cنشده'), ('present', 'حاضر'), ('absent', 'غایب')], default='unmarked', max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='group_classes.groupsessionmeeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='group_classes.groupsessionparticipant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meeting', 'participant')},
            },
        ),
    ]
