# Generated by Django 5.2.15 on 2026-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_classes', '0003_groupsession_price_per_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='is_online',
            field=models.BooleanField(default=False, help_text='آنلاین است — دقیقاً همان شرایط کلاس\u200cهای آنلاین ترمیک را دارد؛ بعد از تایید نهایی، لینک به اپ استاد و شرکت\u200cکننده\u200cها نمایش داده می\u200cشود'),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
