# Generated by Django 5.2.16 on 2026-07-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='شماره کلاس', unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('day_type', models.CharField(choices=[('even', 'روز زوج (سه روز در هفته)'), ('odd', 'روز فرد (سه روز در هفته)'), ('thursday_morning', 'یک روز در هفته - پنجشنبه صبح'), ('thursday_evening', 'یک روز در هفته - پنجشنبه عصر'), ('friday', 'یک روز در هفته - جمعه')], max_length=20)),
                ('is_rotating_majority', models.BooleanField(default=False, help_text='آیا اکثریت این کلاس وضعیت مدرسه\u200cی چرخشی دارند؟')),
                ('student_status', models.CharField(blank=True, choices=[('rotating', 'چرخشی'), ('only_morning', 'فقط صبح'), ('one_day_preference', 'تمایل به کلاس یک روز در هفته'), ('hybrid_online', 'ترکیب حضوری/مجازی و آنلاین'), ('other', 'سایر')], max_length=20)),
                ('student_status_other', models.CharField(blank=True, help_text='توضیح دستی وقتی «سایر» انتخاب شده', max_length=150)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('teacher_name', models.CharField(blank=True, max_length=150)),
                ('time_slot', models.CharField(blank=True, help_text='خودکار محاسبه می\u200cشود، ولی قابل ویرایش دستی هم هست', max_length=20)),
                ('assigned_level', models.CharField(blank=True, max_length=50)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
