# Generated by Django 5.2.16 on 2026-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='شماره کلاس', unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('day_type', models.CharField(choices=[('even', 'روز زوج (سه روز در هفته)'), ('odd', 'روز فرد (سه روز در هفته)'), ('thursday_morning', 'یک روز در هفته - پنجشنبه صبح'), ('thursday_evening', 'یک روز در هفته - پنجشنبه عصر'), ('friday', 'یک روز در هفته - جمعه'), ('online', 'آنلاین'), ('hybrid', 'ترکیبی (آنلاین و حضوری)')], max_length=20)),
                ('time_slot', models.CharField(blank=True, help_text='ساعت جاری کلاس — ترجیحاً از لیست استاندارد', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='توضیحات آزاد، مثلاً «این کلاس فقط بین کلاس ۱ و ۹ جابجا شود»')),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('teacher_name', models.CharField(blank=True, max_length=150)),
                ('assigned_level', models.CharField(blank=True, max_length=50)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
