# Generated by Django 5.2.16 on 2026-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classslot',
            name='number',
            field=models.PositiveIntegerField(help_text='شماره کلاس — همان شماره می\u200cتواند در چند ساعت/روز مختلف تکرار شود (مثلاً کلاس ۱ هم صبح هم عصر)'),
        ),
        migrations.AddConstraint(
            model_name='classslot',
            constraint=models.UniqueConstraint(fields=('number', 'day_type', 'time_slot'), name='unique_class_number_per_day_time', violation_error_message='این شماره کلاس دقیقاً در همین روز و همین ساعت از قبل وجود دارد'),
        ),
    ]
