# Generated by Django 6.0.7 on 2026-07-31 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0002_alter_classslot_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classslot',
            name='gender',
            field=models.CharField(choices=[('girls', 'دخترانه'), ('boys', 'پسرانه'), ('mixed', 'مختلط')], default='mixed', help_text='دخترانه/پسرانه/مختلط — برای جایگذاری صحیح دانش\u200cآموزان', max_length=10),
        ),
        migrations.CreateModel(
            name='ClassSlotEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('pos', 'دستگاه کارت\u200cخوان (پوز)'), ('cash', 'نقدی'), ('gateway', 'درگاه پرداخت آنلاین'), ('card_to_card', 'کارت به کارت'), ('wallet', 'کیف پول')], max_length=20)),
                ('tuition_amount', models.PositiveIntegerField(default=0, help_text='مبلغ شهریه\u200cی پرداختی (تومان)')),
                ('pos_reference_code', models.CharField(blank=True, help_text='کد ساعت/شماره پیگیری دستگاه پوز — فقط وقتی پرداخت از طریق پوز باشد', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class_management.classslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_slot_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('class_slot', 'student'), name='unique_student_per_class_slot')],
            },
        ),
    ]
