# Generated by Django 5.2.15 on 2026-08-02 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0003_classslot_gender_classslotenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classslotenrollment',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='درصد تخفیفی که موقع این ثبت\u200cنام اعمال شد (اگر داشته باشد)'),
        ),
        migrations.CreateModel(
            name='DiscountedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('approved_tuition', models.PositiveIntegerField(default=0, help_text='مبلغ نهایی شهریه بعد از تخفیف، در آخرین ثبت\u200cنامِ دارای تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_records', to='class_management.classslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('card_number', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='class_management.classslot')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TuitionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('E4', 'E4'), ('E5', 'E5'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3'), ('G4', 'G4'), ('G5', 'G5'), ('U1', 'U1'), ('U2', 'U2'), ('U3', 'U3'), ('U4', 'U4'), ('U5', 'U5'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('M5', 'M5'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('Teen1', 'Teen1'), ('Teen2', 'Teen2'), ('Teen3', 'Teen3'), ('Teen4', 'Teen4'), ('Teen5', 'Teen5'), ('Teen6', 'Teen6'), ('Teen7', 'Teen7'), ('Teen8', 'Teen8'), ('Teen9', 'Teen9'), ('Teen10', 'Teen10'), ('Teen11', 'Teen11'), ('Teen12', 'Teen12'), ('Teen13', 'Teen13'), ('Teen14', 'Teen14'), ('Teen15', 'Teen15'), ('101', '101'), ('102', '102'), ('103', '103'), ('104', '104'), ('105', '105'), ('106', '106'), ('201', '201'), ('202', '202'), ('203', '203'), ('204', '204'), ('205', '205'), ('206', '206'), ('301', '301'), ('302', '302'), ('303', '303'), ('304', '304'), ('305', '305'), ('306', '306'), ('401', '401'), ('402', '402'), ('403', '403'), ('404', '404'), ('405', '405'), ('406', '406'), ('501', '501'), ('502', '502'), ('503', '503'), ('504', '504'), ('505', '505'), ('506', '506'), ('601', '601'), ('602', '602'), ('603', '603'), ('604', '604'), ('605', '605'), ('606', '606')], max_length=10)),
                ('age_group', models.CharField(choices=[('kids', 'کودک'), ('teen', 'نوجوان'), ('adult', 'بزرگسال')], max_length=10)),
                ('amount', models.PositiveIntegerField(default=0, help_text='شهریه\u200cی مصوب (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level', 'age_group'],
                'constraints': [models.UniqueConstraint(fields=('level', 'age_group'), name='unique_tuition_per_level_age_group')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('credit', 'واریز به کیف پول'), ('debit', 'برداشت از کیف پول')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='class_management.classslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
