# Generated by Django 5.2.15 on 2026-08-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0004_classslotenrollment_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classslotenrollment',
            name='payment_verified',
            field=models.BooleanField(default=True, help_text='ثبت\u200cنام\u200cهای دستیِ مدیر همیشه تاییدشده\u200cاند؛ ثبت\u200cنام خودِ دانش\u200cآموز (کارت\u200cبه\u200cکارت) تا بررسی رسید توسط مدیر، False می\u200cماند'),
        ),
        migrations.AddField(
            model_name='classslotenrollment',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='تصویر رسید کارت\u200cبه\u200cکارت — فقط برای ثبت\u200cنامِ خودِ دانش\u200cآموز از طریق اپ', null=True, upload_to='enrollment_receipts/'),
        ),
        migrations.AddField(
            model_name='classslotenrollment',
            name='self_enrolled',
            field=models.BooleanField(default=False, help_text='True یعنی خودِ دانش\u200cآموز از طریق اپ ثبت\u200cنام کرده، نه مدیر'),
        ),
    ]
