# Generated by Django 5.2.15 on 2026-08-08 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0006_levelrenewalapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='سال شمسی، مثلاً ۱۴۰۵')),
                ('term_number', models.PositiveSmallIntegerField(help_text='شماره\u200cی ترم، از ۱ تا ۸')),
                ('start_date', models.DateField(help_text='تاریخ شروع ترم (میلادی ذخیره می\u200cشود؛ در پنل به\u200cصورت شمسی وارد/نمایش می\u200cشود)')),
                ('end_date', models.DateField(help_text='تاریخ پایان ترم (میلادی ذخیره می\u200cشود؛ در پنل به\u200cصورت شمسی وارد/نمایش می\u200cشود)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'term_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='classslot',
            name='unique_class_number_per_day_time',
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('year', 'term_number'), name='unique_term_per_year'),
        ),
        migrations.AddField(
            model_name='classslot',
            name='term',
            field=models.ForeignKey(blank=True, help_text='ترمی که این کلاس در آن ساخته شده — کلاس\u200cهای قدیمی\u200cتر از قبل از این قابلیت می\u200cتوانند خالی (بدون ترم) بمانند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_slots', to='class_management.term'),
        ),
        migrations.AddConstraint(
            model_name='classslot',
            constraint=models.UniqueConstraint(fields=('number', 'day_type', 'time_slot', 'term'), name='unique_class_number_per_day_time_term', violation_error_message='این شماره کلاس دقیقاً در همین روز، ساعت و ترم از قبل وجود دارد'),
        ),
    ]
