# Generated by Django 5.2.15 on 2026-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0008_alter_tuitionsetting_level'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classslot',
            name='unique_class_number_per_day_time_term',
        ),
        migrations.AddField(
            model_name='classslot',
            name='is_online',
            field=models.BooleanField(default=False, help_text='کلاس آنلاین است — دقیقاً همان قواعد تشکیل/ثبت\u200cنام کلاس\u200cهای ترمیک حضوری را دارد، فقط با لینک ورود آنلاین'),
        ),
        migrations.AddField(
            model_name='classslot',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='لینک کلاس آنلاین (مثلاً Google Meet/Zoom) — بعد از تایید ثبت\u200cنام، هم به استاد هم به دانش\u200cآموز در اپ نمایش داده می\u200cشود', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='classslot',
            constraint=models.UniqueConstraint(fields=('number', 'day_type', 'time_slot', 'term', 'is_online'), name='unique_class_number_per_day_time_term_mode', violation_error_message='این شماره کلاس دقیقاً در همین روز، ساعت، ترم و حالت (آنلاین/حضوری) از قبل وجود دارد'),
        ),
    ]
