# Generated by Django 5.2.15 on 2026-08-11 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0009_remove_classslot_unique_class_number_per_day_time_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان دوره، مثلاً «دوره فشرده مکالمه تابستانه»', max_length=200)),
                ('price', models.PositiveIntegerField(default=0, help_text='قیمت کل دوره به تومان')),
                ('session_count', models.PositiveIntegerField(default=1, help_text='تعداد جلسات دوره')),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('teacher_name', models.CharField(blank=True, max_length=100)),
                ('schedule_note', models.CharField(blank=True, help_text='زمان\u200cبندی آزاد، مثلاً «سه\u200cشنبه\u200cها ۱۸:۰۰ تا ۱۹:۳۰» — فقط برای هشدار تداخل استاد و نمایش به دانش\u200cآموز استفاده می\u200cشود', max_length=200)),
                ('meeting_link', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='غیرفعال یعنی دیگر توی کاتالوگ دانش\u200cآموز نشان داده نمی\u200cشود (ولی ثبت\u200cنام\u200cهای قبلی می\u200cمانند)')),
                ('internal_number', models.PositiveIntegerField(editable=False, help_text='شماره\u200cی داخلی خودکار — هیچ\u200cجا به کاربر نشان داده نمی\u200cشود، فقط برای یکتایی دیتابیس', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='discountedperson',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_records', to='class_management.onlinecourse'),
        ),
        migrations.AddField(
            model_name='enrollmentrefund',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='class_management.onlinecourse'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='online_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='class_management.onlinecourse'),
        ),
        migrations.CreateModel(
            name='OnlineCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('pos', 'دستگاه کارت\u200cخوان (پوز)'), ('cash', 'نقدی'), ('gateway', 'درگاه پرداخت آنلاین'), ('card_to_card', 'کارت به کارت'), ('wallet', 'کیف پول')], max_length=20)),
                ('price_paid', models.PositiveIntegerField(default=0, help_text='مبلغ نهایی پرداختی (بعد از تخفیف، اگر داشته باشد)')),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='course_receipts/')),
                ('self_enrolled', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(default=True, help_text='ثبت\u200cنام دستی مدیر همیشه تاییدشده؛ ثبت\u200cنام خودِ دانش\u200cآموز تا بررسی رسید False می\u200cماند')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class_management.onlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
