# Generated by Django 5.2.15 on 2026-08-16 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0010_onlinecourse_discountedperson_online_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, help_text='شماره کارت مقصد برای واریز کارت\u200cبه\u200cکارت (بدون خط تیره)', max_length=20)),
                ('card_holder_name', models.CharField(blank=True, help_text='نام و نام\u200cخانوادگیِ صاحب کارت', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='session_date',
            field=models.DateField(blank=True, help_text='تاریخ برگزاری (میلادی ذخیره می\u200cشود؛ در پنل/اپ به\u200cصورت شمسی نمایش داده می\u200cشود) — برای دوره\u200cهای تک\u200cجلسه یا تاریخ شروع دوره\u200cهای چندجلسه\u200cای', null=True),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='session_time',
            field=models.CharField(blank=True, help_text='ساعت برگزاری، مثلاً «18:00-19:30»', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='تاریخ جلسه (میلادی ذخیره می\u200cشود؛ شمسی نمایش داده می\u200cشود)')),
                ('is_present', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class_management.classslot')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('online_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='class_management.onlinecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('class_slot', 'student', 'date'), name='unique_attendance_slot_per_day'), models.UniqueConstraint(fields=('online_course', 'student', 'date'), name='unique_attendance_course_per_day')],
            },
        ),
    ]
