# Generated by Django 5.2.15 on 2026-08-22 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0011_paymentsettings_onlinecourse_session_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourseActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('refund', 'استرداد وجه'), ('transfer', 'انتقال کلاس')], max_length=10)),
                ('card_number', models.CharField(blank=True, max_length=30)),
                ('receiver_name', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید و اجرا شد'), ('rejected', 'رد شد')], default='pending', max_length=10)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('online_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_requests', to='class_management.onlinecourse')),
                ('requested_target_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='class_management.onlinecourse')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_course_action_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
