# Generated by Django 5.2.15 on 2026-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0012_onlinecourseactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='classslot',
            name='previous_teacher_name',
            field=models.CharField(blank=True, help_text='نام استاد کلاس متناظر در ترم قبل برای نمایش راهنما', max_length=150),
        ),
    ]
