# Generated by Django 5.2.15 on 2026-08-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0013_classslot_previous_teacher_name'),
        ('class_management', '0013_classslot_schedule_metadata'),
    ]

    operations = [
    ]
