# Generated by Django 5.2.15 on 2026-08-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0014_merge_20260827_1552'),
        ('class_management', '0014_repair_schedule_columns'),
    ]

    operations = [
    ]
