# Generated by Django 5.2.15 on 2026-08-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0016_teachersessionevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teachersessionevent',
            new_name='class_manag_term_id_ff5582_idx',
            old_name='class_manag_term_id_8d01e3_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersessionevent',
            new_name='class_manag_term_id_185e50_idx',
            old_name='class_manag_term_id_2a5af7_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersessionevent',
            new_name='class_manag_term_id_cde406_idx',
            old_name='class_manag_term_id_5bf702_idx',
        ),
    ]
