# Generated by Django 5.2.17 on 2026-08-29 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0018_alter_level_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomQrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_radius_m', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCompensationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_price', models.PositiveIntegerField(default=0, help_text='قیمت پایهٔ هر جلسه به تومان')),
                ('ordinary_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='ضریب روزهای عادی', max_digits=6)),
                ('thursday_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='ضریب پنجشنبه', max_digits=6)),
                ('friday_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='ضریب جمعه', max_digits=6)),
                ('insurance_base_monthly', models.PositiveIntegerField(default=0, help_text='مزد مبنای بیمهٔ ماهانه؛ صفر یعنی استفاده از ناخالص ترم')),
                ('insurance_rate_percent', models.DecimalField(decimal_places=2, default=7, help_text='درصد بیمهٔ سهم استاد', max_digits=5)),
                ('insurance_days_per_term', models.PositiveIntegerField(default=37, help_text='روز بیمهٔ معادل ترم؛ ترم پیش\u200cفرض یک ماه و یک هفته است')),
                ('allowed_minutes_per_session', models.PositiveIntegerField(default=90, help_text='دقیقهٔ استاندارد هر جلسه برای اتصال آینده به QR')),
                ('adjustment_per_minute', models.PositiveIntegerField(default=0, help_text='تعدیل مبلغ هر دقیقه؛ صفر یعنی قیمت جلسه تقسیم بر دقیقهٔ استاندارد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['teacher__last_name', 'teacher__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('session_number', models.PositiveSmallIntegerField(default=1)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_worked', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='present', max_length=20)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-class_date', 'session_number'],
            },
        ),
        migrations.AddField(
            model_name='teachersessionevent',
            name='class_time',
            field=models.CharField(blank=True, help_text='ساعت واقعی همان جلسه؛ برای پنجشنبه و جمعه از بازه\u200cهای استاندارد انتخاب می\u200cشود', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teachersessionevent',
            constraint=models.UniqueConstraint(fields=('term', 'class_slot', 'event_type', 'class_date', 'session_number'), name='unique_teacher_event_per_session_type'),
        ),
        migrations.AddField(
            model_name='roomqrtoken',
            name='class_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_qr_token', to='class_management.classslot'),
        ),
        migrations.AddField(
            model_name='teachercompensationsetting',
            name='teacher',
            field=models.OneToOneField(limit_choices_to={'role__in': ['teacher', 'evaluator']}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_compensation_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachersessionattendance',
            name='class_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='class_management.classslot'),
        ),
        migrations.AddField(
            model_name='teachersessionattendance',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'evaluator']}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_session_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teachersessionattendance',
            index=models.Index(fields=['class_slot', 'class_date', 'session_number'], name='class_manag_class_s_bc9263_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersessionattendance',
            index=models.Index(fields=['teacher', 'class_date'], name='class_manag_teacher_532d40_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachersessionattendance',
            constraint=models.UniqueConstraint(fields=('class_slot', 'teacher', 'class_date', 'session_number'), name='unique_teacher_attendance_per_session'),
        ),
    ]
