# Generated by Django 5.2.15 on 2026-09-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0020_classattendance_session_status'),
        ('class_management', '0021_alter_tuitionsetting_level_length'),
    ]

    operations = [
    ]
