# Generated by Django 5.2.15 on 2026-09-02 04:55

import level_tests.levels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0022_merge_20260901_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classattendance',
            name='session_number',
        ),
        migrations.RemoveField(
            model_name='classattendance',
            name='status',
        ),
        migrations.AlterField(
            model_name='tuitionsetting',
            name='level',
            field=models.CharField(choices=level_tests.levels.get_all_level_choices, max_length=20),
        ),
    ]
