# Generated by Django 5.2.15 on 2026-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0025_termholiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
