# Generated by Django 5.2.16
# Data migration: FRIDAY_SLOT در models.py قبلاً به‌اشتباه عین THURSDAY_MORNING_SLOT
# ('08:00-13:00') بود؛ همه‌ی کلاس‌های جمعه‌ای که با آن مقدار غلط ساخته شده‌اند اینجا
# به مقدار درست ('08:30-13:15') اصلاح می‌شوند. کلاس‌های جمعه‌ای که دستی با زمان درست
# ساخته شده بودند دست‌نخورده می‌مانند (چون شرط دقیقاً هر دو مقدار day_type و time_slot
# قدیمی را با هم می‌خواهد).

from django.db import migrations


def fix_friday_time_slot(apps, schema_editor):
    ClassSlot = apps.get_model('class_management', 'ClassSlot')
    ClassSlot.objects.filter(day_type='friday', time_slot='08:00-13:00').update(time_slot='08:30-13:15')


def revert_friday_time_slot(apps, schema_editor):
    ClassSlot = apps.get_model('class_management', 'ClassSlot')
    ClassSlot.objects.filter(day_type='friday', time_slot='08:30-13:15').update(time_slot='08:00-13:00')


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0025_termholiday'),
    ]

    operations = [
        migrations.RunPython(fix_friday_time_slot, revert_friday_time_slot),
    ]
