# Generated by Django 5.2.15 on 2026-09-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0026_alter_termholiday_id'),
        ('class_management', '0026_fix_friday_time_slot'),
    ]

    operations = [
    ]
