# Generated by Django 5.2.15 on 2026-10-10 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0030_classslotenrollment_carryover_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classattendance',
            name='unique_attendance_slot_per_day',
        ),
        migrations.AddField(
            model_name='classattendance',
            name='session_in_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='classattendance',
            constraint=models.UniqueConstraint(fields=('class_slot', 'student', 'date', 'session_in_day'), name='unique_attendance_slot_per_day'),
        ),
    ]
