# Generated by Django 5.2.15 on 2026-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_webpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
