from django.urls import path
from .views import (
    ClassSlotListView, ClassSlotDetailView, AllocateClassesView,
    ConfirmOverflowView, TransferSurplusView, SpinOffSurplusView, ClassStatsView,
    BulkCreatePhysicalClassesView, ClassSlotEnrollView, ClassSlotUnenrollView, ClassSlotRosterView,
    TuitionSuggestionView, TuitionSettingListView, TuitionSettingDetailView, DiscountedPersonListView,
    RefundEnrollmentView, TransferEnrollmentOptionsView, TransferEnrollmentView, CreditToWalletView,
    StudentFinancialHistoryView, EnrollmentReportView, SplitClassView, DirectEnrollSuggestionsView,
    MyDirectEnrollSuggestionsView, SelfEnrollView, VerifyEnrollmentPaymentView,
)

urlpatterns = [
    path('class-management/slots/', ClassSlotListView.as_view(), name='class_slot_list'),
    path('class-management/slots/<int:pk>/', ClassSlotDetailView.as_view(), name='class_slot_detail'),
    path('class-management/slots/<int:pk>/transfer-surplus/', TransferSurplusView.as_view(), name='class_transfer_surplus'),
    path('class-management/slots/<int:pk>/spin-off-surplus/', SpinOffSurplusView.as_view(), name='class_spin_off_surplus'),
    path('class-management/slots/<int:pk>/enroll/', ClassSlotEnrollView.as_view(), name='class_slot_enroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/', ClassSlotUnenrollView.as_view(), name='class_slot_unenroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/refund/', RefundEnrollmentView.as_view(), name='class_slot_refund'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/transfer-options/', TransferEnrollmentOptionsView.as_view(), name='class_slot_transfer_options'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/transfer/', TransferEnrollmentView.as_view(), name='class_slot_transfer'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/to-wallet/', CreditToWalletView.as_view(), name='class_slot_to_wallet'),
    path('class-management/slots/<int:pk>/roster/', ClassSlotRosterView.as_view(), name='class_slot_roster'),
    path('class-management/slots/<int:pk>/tuition-suggestion/', TuitionSuggestionView.as_view(), name='class_tuition_suggestion'),
    path('class-management/bulk-create/', BulkCreatePhysicalClassesView.as_view(), name='class_bulk_create'),
    path('class-management/allocate/', AllocateClassesView.as_view(), name='class_allocate'),
    path('class-management/allocate/confirm-overflow/', ConfirmOverflowView.as_view(), name='class_confirm_overflow'),
    path('class-management/stats/', ClassStatsView.as_view(), name='class_stats'),
    path('class-management/tuition-settings/', TuitionSettingListView.as_view(), name='tuition_setting_list'),
    path('class-management/tuition-settings/<int:pk>/', TuitionSettingDetailView.as_view(), name='tuition_setting_detail'),
    path('class-management/discounted-persons/', DiscountedPersonListView.as_view(), name='discounted_person_list'),
    path('class-management/students/<int:student_id>/financial-history/', StudentFinancialHistoryView.as_view(), name='student_financial_history'),
    path('class-management/slots/<int:pk>/split/', SplitClassView.as_view(), name='class_slot_split'),
    path('class-management/direct-enroll-suggestions/', DirectEnrollSuggestionsView.as_view(), name='direct_enroll_suggestions'),
    path('class-management/my-direct-enroll-suggestions/', MyDirectEnrollSuggestionsView.as_view(), name='my_direct_enroll_suggestions'),
    path('class-management/slots/<int:pk>/self-enroll/', SelfEnrollView.as_view(), name='class_slot_self_enroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/verify-payment/', VerifyEnrollmentPaymentView.as_view(), name='class_slot_verify_payment'),
    path('class-management/enrollment-report/', EnrollmentReportView.as_view(), name='enrollment_report'),
]
