from django.urls import path
from .views import (
    ClassSlotListView, ClassSlotDetailView, SwapClassLocationView, TransferClassLocationView, AllocateClassesView,
    ConfirmOverflowView, TransferSurplusView, SpinOffSurplusView, ClassStatsView,
    BulkCreatePhysicalClassesView, ClassSlotEnrollView, ClassSlotUnenrollView, ClassSlotRosterView,
    TuitionSuggestionView, TuitionSettingListView, TuitionSettingDetailView, DiscountedPersonListView, DiscountedPersonDetailView,
    RefundEnrollmentView, TransferEnrollmentOptionsView, TransferEnrollmentView, CreditToWalletView,
    StudentFinancialHistoryView, EnrollmentReportView, SplitClassView, DirectEnrollSuggestionsView,
    MyDirectEnrollSuggestionsView, SelfEnrollView, VerifyEnrollmentPaymentView, MyEnrollmentsView,
    LevelRenewalApprovalListView, LevelRenewalApprovalDecideView,
    PendingSelfEnrollmentsView, RejectPendingEnrollmentView, StudentEducationHistoryView,
    TermListView, TermDetailView, CarryClassesToNextTermView, TeacherEducationHistoryView, TeacherTermClassesView,
    OnlineCourseListView, OnlineCourseDetailView, OnlineCourseCatalogView, OnlineCourseEnrollView,
    OnlineCourseSelfEnrollView, PendingOnlineCourseEnrollmentsView, VerifyOnlineCourseEnrollmentPaymentView,
    RejectPendingOnlineCourseEnrollmentView, RefundOnlineCourseEnrollmentView, CreditOnlineCourseToWalletView,
    MyOnlineCourseEnrollmentsView, TeacherOnlineCoursesView, GatewayPaymentInitiateView, PaymentSettingsView,
    MarkAttendanceView, ClassAttendanceListView, BulkClassSlotActionView,
    OnlineCourseRosterView, OnlineCourseUnenrollView, OnlineCourseTransferOptionsView, OnlineCourseTransferView,
    StudentCreateOnlineCourseActionRequestView, MyOnlineCourseActionRequestsView,
    AdminOnlineCourseActionRequestListView, ApproveOnlineCourseActionRequestView, RejectOnlineCourseActionRequestView,
    TeacherTermReportView, TeacherSessionEventListCreateView, TeacherSessionEventDetailView,
    RoomQrManageView, TeacherQrAttendanceView, TeacherSessionAttendanceListView, TeacherCompensationSettingsView,
)

urlpatterns = [
    path('class-management/slots/', ClassSlotListView.as_view(), name='class_slot_list'),
    path('class-management/slots/<int:pk>/', ClassSlotDetailView.as_view(), name='class_slot_detail'),
    path('class-management/slots/<int:pk>/swap-location/', SwapClassLocationView.as_view(), name='class_slot_swap_location'),
    path('class-management/slots/<int:pk>/transfer-location/', TransferClassLocationView.as_view(), name='class_slot_transfer_location'),
    path('class-management/slots/<int:pk>/transfer-surplus/', TransferSurplusView.as_view(), name='class_transfer_surplus'),
    path('class-management/slots/<int:pk>/spin-off-surplus/', SpinOffSurplusView.as_view(), name='class_spin_off_surplus'),
    path('class-management/slots/<int:pk>/enroll/', ClassSlotEnrollView.as_view(), name='class_slot_enroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/', ClassSlotUnenrollView.as_view(), name='class_slot_unenroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/refund/', RefundEnrollmentView.as_view(), name='class_slot_refund'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/transfer-options/', TransferEnrollmentOptionsView.as_view(), name='class_slot_transfer_options'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/transfer/', TransferEnrollmentView.as_view(), name='class_slot_transfer'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/to-wallet/', CreditToWalletView.as_view(), name='class_slot_to_wallet'),
    path('class-management/slots/<int:pk>/roster/', ClassSlotRosterView.as_view(), name='class_slot_roster'),
    path('class-management/slots/<int:pk>/tuition-suggestion/', TuitionSuggestionView.as_view(), name='class_tuition_suggestion'),
    path('class-management/bulk-create/', BulkCreatePhysicalClassesView.as_view(), name='class_bulk_create'),
    path('class-management/allocate/', AllocateClassesView.as_view(), name='class_allocate'),
    path('class-management/allocate/confirm-overflow/', ConfirmOverflowView.as_view(), name='class_confirm_overflow'),
    path('class-management/stats/', ClassStatsView.as_view(), name='class_stats'),
    path('class-management/tuition-settings/', TuitionSettingListView.as_view(), name='tuition_setting_list'),
    path('class-management/tuition-settings/<int:pk>/', TuitionSettingDetailView.as_view(), name='tuition_setting_detail'),
    path('class-management/discounted-persons/', DiscountedPersonListView.as_view(), name='discounted_person_list'),
    path('class-management/discounted-persons/<int:pk>/', DiscountedPersonDetailView.as_view(), name='discounted_person_detail'),
    path('class-management/students/<int:student_id>/financial-history/', StudentFinancialHistoryView.as_view(), name='student_financial_history'),
    path('class-management/slots/<int:pk>/split/', SplitClassView.as_view(), name='class_slot_split'),
    path('class-management/direct-enroll-suggestions/', DirectEnrollSuggestionsView.as_view(), name='direct_enroll_suggestions'),
    path('class-management/my-direct-enroll-suggestions/', MyDirectEnrollSuggestionsView.as_view(), name='my_direct_enroll_suggestions'),
    path('class-management/my-enrollments/', MyEnrollmentsView.as_view(), name='my_enrollments'),
    path('class-management/level-renewal-requests/', LevelRenewalApprovalListView.as_view(), name='level_renewal_list'),
    path('class-management/level-renewal-requests/<int:pk>/decide/', LevelRenewalApprovalDecideView.as_view(), name='level_renewal_decide'),
    path('class-management/slots/<int:pk>/self-enroll/', SelfEnrollView.as_view(), name='class_slot_self_enroll'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/verify-payment/', VerifyEnrollmentPaymentView.as_view(), name='class_slot_verify_payment'),
    path('class-management/slots/<int:pk>/enroll/<int:student_id>/reject-pending/', RejectPendingEnrollmentView.as_view(), name='class_slot_reject_pending'),
    path('class-management/pending-self-enrollments/', PendingSelfEnrollmentsView.as_view(), name='pending_self_enrollments'),
    path('class-management/students/<int:student_id>/education-history/', StudentEducationHistoryView.as_view(), name='student_education_history'),
    path('class-management/enrollment-report/', EnrollmentReportView.as_view(), name='enrollment_report'),
    path('class-management/terms/', TermListView.as_view(), name='term_list'),
    path('class-management/terms/<int:pk>/', TermDetailView.as_view(), name='term_detail'),
    path('class-management/terms/carry-classes/', CarryClassesToNextTermView.as_view(), name='carry_classes_to_next_term'),
    path('class-management/teachers/<int:teacher_id>/education-history/', TeacherEducationHistoryView.as_view(), name='teacher_education_history'),
    path('class-management/my-term-classes/', TeacherTermClassesView.as_view(), name='my_term_classes'),
    path('class-management/teacher-term-report/', TeacherTermReportView.as_view(), name='teacher_term_report'),
    path('class-management/teacher-session-events/', TeacherSessionEventListCreateView.as_view(), name='teacher_session_event_list_create'),
    path('class-management/teacher-session-events/<int:pk>/', TeacherSessionEventDetailView.as_view(), name='teacher_session_event_detail'),
    path('class-management/slots/<int:pk>/room-qr/', RoomQrManageView.as_view(), name='room_qr_manage'),
    path('class-management/teacher-qr-attendance/', TeacherQrAttendanceView.as_view(), name='teacher_qr_attendance'),
    path('class-management/teacher-attendance-records/', TeacherSessionAttendanceListView.as_view(), name='teacher_attendance_records'),
    path('class-management/teacher-compensation-settings/', TeacherCompensationSettingsView.as_view(), name='teacher_compensation_settings'),

    # --- سایر دوره‌ها / کلاس‌های علمی (OnlineCourse) ---
    path('class-management/courses/', OnlineCourseListView.as_view(), name='online_course_list'),
    path('class-management/courses/<int:pk>/', OnlineCourseDetailView.as_view(), name='online_course_detail'),
    path('class-management/courses-catalog/', OnlineCourseCatalogView.as_view(), name='online_course_catalog'),
    path('class-management/courses/<int:pk>/enroll/', OnlineCourseEnrollView.as_view(), name='online_course_enroll'),
    path('class-management/courses/<int:pk>/self-enroll/', OnlineCourseSelfEnrollView.as_view(), name='online_course_self_enroll'),
    path('class-management/pending-course-enrollments/', PendingOnlineCourseEnrollmentsView.as_view(), name='pending_course_enrollments'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/verify-payment/', VerifyOnlineCourseEnrollmentPaymentView.as_view(), name='online_course_verify_payment'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/reject-pending/', RejectPendingOnlineCourseEnrollmentView.as_view(), name='online_course_reject_pending'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/refund/', RefundOnlineCourseEnrollmentView.as_view(), name='online_course_refund'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/to-wallet/', CreditOnlineCourseToWalletView.as_view(), name='online_course_to_wallet'),
    path('class-management/courses/<int:pk>/roster/', OnlineCourseRosterView.as_view(), name='online_course_roster'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/remove/', OnlineCourseUnenrollView.as_view(), name='online_course_unenroll'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/transfer-options/', OnlineCourseTransferOptionsView.as_view(), name='online_course_transfer_options'),
    path('class-management/courses/<int:pk>/enroll/<int:student_id>/transfer/', OnlineCourseTransferView.as_view(), name='online_course_transfer'),
    path('class-management/course-action-requests/', StudentCreateOnlineCourseActionRequestView.as_view(), name='online_course_action_request_create'),
    path('class-management/my-course-action-requests/', MyOnlineCourseActionRequestsView.as_view(), name='my_online_course_action_requests'),
    path('class-management/admin-course-action-requests/', AdminOnlineCourseActionRequestListView.as_view(), name='admin_online_course_action_requests'),
    path('class-management/admin-course-action-requests/<int:pk>/approve/', ApproveOnlineCourseActionRequestView.as_view(), name='approve_online_course_action_request'),
    path('class-management/admin-course-action-requests/<int:pk>/reject/', RejectOnlineCourseActionRequestView.as_view(), name='reject_online_course_action_request'),
    path('class-management/my-course-enrollments/', MyOnlineCourseEnrollmentsView.as_view(), name='my_course_enrollments'),
    path('class-management/my-online-courses/', TeacherOnlineCoursesView.as_view(), name='teacher_online_courses'),
    path('class-management/gateway-payment/initiate/', GatewayPaymentInitiateView.as_view(), name='gateway_payment_initiate'),
    path('class-management/payment-settings/', PaymentSettingsView.as_view(), name='payment_settings'),
    path('class-management/attendance/mark/', MarkAttendanceView.as_view(), name='mark_attendance'),
    path('class-management/attendance/', ClassAttendanceListView.as_view(), name='attendance_list'),
    path('class-management/slots/bulk-action/', BulkClassSlotActionView.as_view(), name='bulk_class_slot_action'),
]
